apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: otaqs.aquakube.io
  labels:
    app.kubernetes.io/name: otaq
    app.kubernetes.io/managed-by: aquakube
    app.kubernetes.io/part-of: aquakube
    app.kubernetes.io/component: crd
spec:
  group: aquakube.io
  scope: Namespaced
  names:
    plural: otaqs
    singular: otaq
    kind: OTAQ
    shortNames:
    - eagle
    categories:
    - cameras
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: >-
            An OTAQ is a camera deployed to avalon cages to monitor fish remotely.
            This resource is created and managed by field service personnel.
            This resource will kick off a workflow to provision and configure the camera.
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  description: >-
                    The name of the OTAQ device.
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: >-
                    The phase the camera is in (e.g 'provisioning', 
                    'provisioned', 'provisioning_failed', etc)
                conditions:
                  type: array
                  description: >-
                    A todo item.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: >-
                          A provision / configuration type definition.
                      status:
                        type: string
                        description: >-
                          Status of the condition, one of True, False, Unknown.
                      reason:
                        type: string
                        description: >-
                          The reason for the condition's last transition.
                      message:
                        type: string
                        description: >-
                          A human readable message
                      lastTransitionTime:
                        type: string
                        description: >-
                          Last time the condition transitioned from one status to another.
                      lastUpdateTime:
                        type: string
                        description: >-
                          The last time this condition was updated.
            spec:
              description: >-
                OTAQSpec defines the desired state of the OTAQ camera.
              type: object
              properties:
                workflow:
                  type: object
                  required:
                    - version
                    - provision_strategy
                  description: >-
                    The workflow configuration for the OTAQ camera.
                  properties:
                    version:
                      type: string
                      description: >-
                        The workflow verison (e.g '1.1.2'). This cooresponds to the
                        semantically versioned code that will be utilized in the
                        provisioning workflow.
                    force_provision:
                      type: boolean
                      default: false
                      description: >-
                        Force the provisioning of this device even if the firmware
                        version discovered is not recognized.
                    provision_strategy:
                      type: string
                      enum: ["resolve_mac_address", "dhcp_ip_address"]
                      description: >-
                        The strategy to use when provisioning the OTAQ.
                        One of ["resolve_mac_address", "dhcp_ip_address"].
                        "resolve_mac_address" will attempt to use the provided mac_address
                        and subnet to resolve the ip address for provisioning.
                        "dhcp_ip_address" will use the provided dhcp ip address to
                        provision the device.
                network:
                  type: object
                  required:
                    - mode
                  description: >-
                    The network configuration for the OTAQ camera.
                  properties:
                    mode:
                      type: string
                      enum: ["static", "dhcp"]
                      description: >-
                        The network mode to use for the OTAQ. One of ["static", "dhcp"].
                        "static" will assign the provided static ip address to the camera, 
                        requires field 'static_ip_address' to be set for configuration. 
                        "dhcp" will not update any settings and simply use dhcp networking.
                    mac_address:
                      type: string
                      description: >-
                        The MAC address of the OTAQ.
                        This field must be set when using provision_strategy "resolve_mac_address".
                    dhcp_ip_address:
                      type: string
                      description: >-
                        The ip address to utilize when provisioning the device. This is only
                        used if the "provision_strategy" is "dhcp_ip_address"
                    subnet:
                      type: string
                      description: >-
                        The subnet the camera is hosted on (e.g 10.0.9.0/24). This is only used
                        if the "provision_strategy" is "resolve_mac_address". In this strategy,
                        the entire subnet will be scanned to find the mac address.
                    static_ip_address:
                      type: string
                      description: >-
                        The static ip address to assign to this device. This is only used
                        if the network "mode" is "static"
                video:
                  type: object
                  description: >-
                    The video configuration for the OTAQ camera.
                  properties:
                    framerate:
                      type: integer
                      enum: [15, 30]
                      default: 15
                      description: >-
                        The framerate of the video stream. One of [15, 30]
                    quality:
                      type: integer
                      enum: [1, 2, 3, 4, 5, 6]
                      default: 4
                      description: >-
                        The quality of the video stream. One of [1, 2, 3, 4, 5, 6]
                    resolution:
                      type: string
                      enum: ['1080P', '4K', '5M']
                      default: 1080P
                      description: >-
                        The resolution of the video stream. One of ['1080P', '4K', '5M']
                    gop:
                      type: integer
                      minimum: 1
                      maximum: 30
                      default: 1
                      description: >-
                        The gop of the video stream.
                    bitrate_controller:
                      type: string
                      enum: ['CBR', 'VBR']
                      default: VBR
                      description: >-
                        The bit rate control for the video stream. One of ['CBR', 'VBR']
                    compression:
                      type: string
                      enum: ['H.264', 'H.265']
                      default: H.264
                      description: >-
                        The compression for the video stream. One of ['H.264', 'H.265']
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Version
          type: string
          description: The workflow version
          jsonPath: .spec.workflow.version
        - name: Phase
          type: string
          description: The current phase of the OTAQ camera workflow
          jsonPath: .status.phase