apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  labels:
    app.kubernetes.io/name: workflow
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workflow
    spec:
      imagePullSecrets:
      - name: k8s-ecr-login-renew-docker-secret
      containers:
        - name: workflow
          image: 456087932636.dkr.ecr.us-west-2.amazonaws.com/kube-otaq/workflow
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"