apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otaq

commonLabels:
  app.kubernetes.io/name: workflow
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: workflow
  app.kubernetes.io/part-of: otaq

resources:
  - deployment.yaml