apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otaq-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otaq-operator
subjects:
  - kind: ServiceAccount
    name: otaq-operator
    namespace: otaq