apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otaq

commonLabels:
  app.kubernetes.io/name: otaq-operator
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: otaq

resources:
  - cluster-role.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
